apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgCSJhdXRoIjogImJXbG9ZV2xzYzJWeVoyVmxibXR2ZGpwbmFIQmZNRVoyUmpKYU9IUjZhVkZVZEZGR2J6aHRhMWcwYjJGWk5EaEJSM2hDTkZSdE5GVlUiCiAgICAgICAgICAgICAgICB9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson
